default:
    name:                   secret_sauce
    type:                   configuration
    name_suffix:            _default

    locale:                 en_EN.UTF-8
    country:                EN

    applications:
        secret_sauce:
            web:
                uwsgi_port:     8999
                url:            secret_sauce.lab

    extra_files:
        -   name:                   secret_sauce_web
            type:                   nginx
            template:               templates/nginx.conf

live:
    name_suffix:            _live

    applications:
        secret_sauce:
            web:
                uwsgi_port:     8998
                url:            a_secret_sauce.com
